route:
  receiver: 'mail'
  repeat_interval: 4h
  group_by: [ alertname ]


receivers:
  - name: 'mail'
    email_configs:
      - smarthost: 'smtp.gmail.com:465'
        auth_username: 'Pythonprtgs@gmail.com'
        auth_password_file: '/etc/alertmanager/alertmanager_password.txt'
        from: 'Pythonprtgs@gmail.com'
        to: 'Pythonprtgs@gmail.com'